name: flutter_matter_platfrom_interface
description: A common platform interface for the flutter_matter plugin.
# repository:
# issue_tracker:
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  checks: ^0.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

topics:
  - matter
  - smart-home
  - smarthome
  - iot
  - device
  - commission
  - control
  - share
  - wifi
  - thread
  - open-thread
