name: flutter_matter_android
description: Android implementation of the flutter_matter plugin.
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_matter_platfrom_interface: ^0.0.1
  rxdart: ^0.27.7

dev_dependencies:
  async: ^2.11.0
  build_runner: ^2.4.6
  checks: ^0.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  pigeon: ^11.0.1
  plugin_platform_interface: ^2.1.6

flutter:
  plugin:
    platforms:
      android:
        package: net.grandcentrix.flutter_matter
        pluginClass: FlutterMatterPlugin

topics:
  - matter
  - smart-home
  - smarthome
  - iot
  - device
  - commission
  - control
  - share
  - wifi
  - thread
  - open-thread
