// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_matter_android/test/src/clusters/flutter_matter_android_onoff_cluster_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_matter_android/src/flutter_matter.g.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FlutterMatterHostOnOffClusterApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterMatterHostOnOffClusterApi extends _i1.Mock
    implements _i2.FlutterMatterHostOnOffClusterApi {
  @override
  _i3.Future<void> off(
    int? arg_deviceId,
    int? arg_endpointId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #off,
          [
            arg_deviceId,
            arg_endpointId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> on(
    int? arg_deviceId,
    int? arg_endpointId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #on,
          [
            arg_deviceId,
            arg_endpointId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> toggle(
    int? arg_deviceId,
    int? arg_endpointId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggle,
          [
            arg_deviceId,
            arg_endpointId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<bool> readOnOff(
    int? arg_deviceId,
    int? arg_endpointId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #readOnOff,
          [
            arg_deviceId,
            arg_endpointId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
